package U.seriesDeTv;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.scene.control.Label;

import javafx.scene.control.ListView;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.MenuButton;
import javafx.scene.control.MenuItem;

public class SampleController {
	@FXML
	private TextField nomSerie;
	@FXML
	private MenuButton menuButton;
	@FXML
	private Label castella;
	@FXML
	private Label sub;
	@FXML
	private Label angles;
	@FXML
	private ListView listMenu;
	ObservableList <MenuItem> temporadas = FXCollections.observableArrayList();


	public SampleController() {
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void clickBuscar(ActionEvent event) {
		// TODO Autogenerated
		String busca = nomSerie.getText();
		//WebDriver navi = new HtmlUnitDriver();
		WebDriver navi = new FirefoxDriver();
		navi.navigate().to("http://seriesblanco.com/");
		navi.findElement(By.id("buscar-blanco")).sendKeys(busca+(Keys.RETURN));
		navi.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		navi. findElement(By.className("ict")).click();
		
		for(WebElement element: navi.findElements(By.xpath("//h2/u"))) {
			MenuItem p = new MenuItem(element.getText());
			p.setOnAction(actionEvent -> { carregarCapitols(p.getText(), navi); } );
			temporadas.add(p);
		}
		menuButton.getItems().clear();
		menuButton.getItems().addAll(temporadas);
		
	}
	
	private void carregarCapitols(String text, WebDriver navi) {
		navi. findElement(By.cssSelector("#zebra tbody tr td a")).click();
		
	}
	// Event Listener on MenuButton[#menuButton].onAction
	@FXML
	public void clicMenuButton(ActionEvent event) {
		
	}
	// Event Listener on ListView[#listMenu].onMouseClicked
	@FXML
	public void clicListMenu(MouseEvent event) {
		// TODO Autogenerated
	}
}
