package U.seriesDeTv;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.MenuButton;

public class SampleController {
	@FXML
	private TextField nomSerie;
	@FXML
	private MenuButton menuButton;
	@FXML
	private Label castella;
	@FXML
	private Label sub;
	@FXML
	private Label angles;
	@FXML
	private ListView listMenu;

	// Event Listener on Button.onAction
	@FXML
	public void clickBuscar(ActionEvent event) {
		// TODO Autogenerated
		String busca = nomSerie.getText();
		//WebDriver navi = new HtmlUnitDriver();
		WebDriver navi = new FirefoxDriver();
		navi.navigate().to("http://seriesblanco.com/");
		navi.findElement(By.id("buscar-blanco")).sendKeys(busca+(Keys.RETURN));
	}
	// Event Listener on MenuButton[#menuButton].onAction
	@FXML
	public void clicMenuButton(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ListView[#listMenu].onMouseClicked
	@FXML
	public void clicListMenu(MouseEvent event) {
		// TODO Autogenerated
	}
}
